name = "test_symbac_width_0.9_length_2"

[simulation]
trench_length=15
trench_width=1.15
cell_max_length=2 #6 long cells # 1.65 short cells
cell_width= 0.90 #1 long cells # 0.95 short cells
sim_length = 20
pix_mic_conv = 0.065
gravity=0
phys_iters=15
max_length_var = 0
width_var = 0
lysis_p = 0
save_dir="./tmp/"
resize_amount = 3

[phase_psf]
radius = 50 
wavelength = 0.75 
NA = 1.2 
n = 1.3 
resize_amount = 3 
pix_mic_conv = 0.065 
apo_sigma = 20 
mode="phase contrast"
condenser = "Ph3"

[fluo_psf]
radius = 50 
wavelength = 0.75 
NA = 1.2 
n = 1.3 
resize_amount = 3 
pix_mic_conv = 0.065 
apo_sigma = 20 
mode="simple fluo"
condenser = "Ph3"

[camera]
baseline=100 
sensitivity=2.9
dark_noise=8

[fluo_image_stats]
media_mean = 0.1
media_var = 0.05
cell_mean = 0.8
cell_var = 0.1
device_mean = 0.1
device_var = 0.05

[phase_image_stats]
media_mean = 0.9
media_var = 0.05
cell_mean = 0.3
cell_var = 0.1
device_mean = 0.05
device_var = 0.01

[training_data]
sample_amount=0.05
burn_in=0
n_samples = 10
save_dir="./symbac_video_test_output/"
in_series=false
n_jobs = 1

[renderer]
media_multiplier=75
cell_multiplier=1.7
device_multiplier=29
sigma=8.85
defocus=3
halo_top_intensity = 1 
halo_bottom_intensity = 1
halo_start = 0
halo_end = 1
noise_var = 0