name = "video_one"

[simulation]
trench_length=15
trench_width=1.15
cell_max_length=[2,5] #6 long cells # 1.65 short cells
cell_width= [0.89, 0.98] #1 long cells # 0.95 short cells
sim_length = 100
pix_mic_conv = 0.065
gravity=0
phys_iters=15
max_length_var = 0
width_var = 0
lysis_p = 0
resize_amount = 3

[phase_psf]
radius = 50 
wavelength = 0.75 
NA = 1.2 
n = 1.3 
resize_amount = 3 
pix_mic_conv = 0.065 
apo_sigma = 20 
mode="phase contrast"
condenser = "Ph3"

[camera]
baseline=100 
sensitivity=2.9
dark_noise=8

[phase_image_stats]
filepath = ["images/220510_bsub_degron_rap_BF_raw.tif", "images/210214_salmonella_BF_raw.tif"]
media_mean = 0.1
media_var = 0.05
cell_mean = 0.3
cell_var = 0.1
device_mean = 0.05
device_var = 0.01

[training_data]
burn_in=0
num_scenes = 100
save_dir="/nrs/funke/data/darts/synthetic_data/"

[renderer]
media_multiplier=75
cell_multiplier=1.7
device_multiplier=29
sigma=8.82
defocus=3
halo_top_intensity = 1 
halo_bottom_intensity = 1
halo_start = 0.77
halo_end = 1
noise_var = 0